name: Hello World WS

on:
  push:
    branches:
     - main
    
jobs:
  echo_hello_actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print Hello Actions
        run: echo Hello Actions!
