name: Hello World WS

on:
  push:
    branches:
     - main
    
jobs:
  echo_hello_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Actions
        run: echo Hello Actions!
      - name: LS teste
        run: ls -la
